# ####################################################################

#  Created by Genus(TM) Synthesis Solution 25.12-s067_1 on Mon Apr 20 23:48:07 CST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design flash_attention_top

create_clock -name "clk" -period 10.0 -waveform {0.0 5.0} [get_ports clk]
set_clock_transition 0.1 [get_clocks clk]
set_load -pin_load 0.02 [get_ports s_axil_awready]
set_load -pin_load 0.02 [get_ports s_axil_wready]
set_load -pin_load 0.02 [get_ports {s_axil_bresp[1]}]
set_load -pin_load 0.02 [get_ports {s_axil_bresp[0]}]
set_load -pin_load 0.02 [get_ports s_axil_bvalid]
set_load -pin_load 0.02 [get_ports s_axil_arready]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[31]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[30]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[29]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[28]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[27]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[26]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[25]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[24]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[23]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[22]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[21]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[20]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[19]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[18]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[17]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[16]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[15]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[14]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[13]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[12]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[11]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[10]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[9]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[8]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[7]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[6]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[5]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[4]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[3]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[2]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[1]}]
set_load -pin_load 0.02 [get_ports {s_axil_rdata[0]}]
set_load -pin_load 0.02 [get_ports {s_axil_rresp[1]}]
set_load -pin_load 0.02 [get_ports {s_axil_rresp[0]}]
set_load -pin_load 0.02 [get_ports s_axil_rvalid]
set_load -pin_load 0.02 [get_ports {m_axi_awid[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_awid[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_awid[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_awid[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[63]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[62]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[61]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[60]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[59]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[58]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[57]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[56]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[55]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[54]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[53]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[52]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[51]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[50]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[49]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[48]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[47]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[46]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[45]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[44]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[43]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[42]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[41]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[40]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[39]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[38]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[37]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[36]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[35]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[34]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[33]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[32]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[31]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[30]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[29]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[28]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[27]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[26]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[25]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[24]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[23]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[22]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[21]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[20]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[19]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[18]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[17]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[16]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[15]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[14]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[13]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[12]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[11]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[10]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[9]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[8]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[7]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[6]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[5]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[4]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_awaddr[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[7]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[6]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[5]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[4]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_awlen[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_awsize[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_awsize[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_awsize[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_awburst[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_awburst[0]}]
set_load -pin_load 0.02 [get_ports m_axi_awvalid]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[127]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[126]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[125]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[124]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[123]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[122]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[121]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[120]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[119]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[118]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[117]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[116]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[115]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[114]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[113]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[112]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[111]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[110]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[109]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[108]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[107]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[106]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[105]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[104]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[103]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[102]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[101]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[100]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[99]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[98]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[97]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[96]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[95]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[94]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[93]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[92]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[91]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[90]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[89]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[88]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[87]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[86]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[85]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[84]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[83]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[82]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[81]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[80]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[79]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[78]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[77]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[76]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[75]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[74]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[73]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[72]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[71]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[70]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[69]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[68]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[67]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[66]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[65]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[64]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[63]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[62]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[61]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[60]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[59]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[58]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[57]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[56]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[55]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[54]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[53]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[52]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[51]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[50]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[49]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[48]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[47]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[46]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[45]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[44]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[43]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[42]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[41]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[40]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[39]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[38]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[37]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[36]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[35]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[34]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[33]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[32]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[31]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[30]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[29]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[28]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[27]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[26]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[25]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[24]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[23]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[22]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[21]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[20]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[19]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[18]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[17]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[16]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[15]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[14]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[13]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[12]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[11]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[10]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[9]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[8]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[7]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[6]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[5]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[4]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_wdata[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[15]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[14]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[13]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[12]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[11]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[10]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[9]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[8]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[7]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[6]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[5]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[4]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_wstrb[0]}]
set_load -pin_load 0.02 [get_ports m_axi_wlast]
set_load -pin_load 0.02 [get_ports m_axi_wvalid]
set_load -pin_load 0.02 [get_ports m_axi_bready]
set_load -pin_load 0.02 [get_ports {m_axi_arid[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_arid[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_arid[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_arid[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[63]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[62]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[61]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[60]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[59]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[58]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[57]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[56]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[55]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[54]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[53]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[52]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[51]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[50]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[49]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[48]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[47]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[46]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[45]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[44]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[43]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[42]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[41]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[40]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[39]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[38]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[37]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[36]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[35]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[34]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[33]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[32]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[31]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[30]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[29]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[28]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[27]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[26]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[25]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[24]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[23]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[22]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[21]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[20]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[19]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[18]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[17]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[16]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[15]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[14]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[13]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[12]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[11]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[10]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[9]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[8]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[7]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[6]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[5]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[4]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_araddr[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[7]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[6]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[5]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[4]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[3]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_arlen[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_arsize[2]}]
set_load -pin_load 0.02 [get_ports {m_axi_arsize[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_arsize[0]}]
set_load -pin_load 0.02 [get_ports {m_axi_arburst[1]}]
set_load -pin_load 0.02 [get_ports {m_axi_arburst[0]}]
set_load -pin_load 0.02 [get_ports m_axi_arvalid]
set_load -pin_load 0.02 [get_ports m_axi_rready]
set_load -pin_load 0.02 [get_ports irq]
set_false_path -from [get_ports rst_n]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_awaddr[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_awvalid]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wdata[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wstrb[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wstrb[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wstrb[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_wstrb[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_wvalid]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_bready]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_araddr[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_arvalid]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_rready]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_awready]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_wready]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_bid[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_bid[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_bid[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_bid[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_bresp[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_bresp[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_bvalid]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_arready]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rid[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rid[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rid[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rid[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[127]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[126]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[125]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[124]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[123]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[122]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[121]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[120]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[119]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[118]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[117]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[116]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[115]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[114]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[113]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[112]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[111]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[110]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[109]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[108]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[107]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[106]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[105]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[104]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[103]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[102]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[101]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[100]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[99]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[98]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[97]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[96]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[95]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[94]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[93]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[92]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[91]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[90]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[89]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[88]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[87]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[86]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[85]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[84]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[83]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[82]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[81]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[80]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[79]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[78]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[77]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[76]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[75]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[74]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[73]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[72]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[71]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[70]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[69]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[68]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[67]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[66]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[65]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[64]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[63]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[62]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[61]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[60]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[59]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[58]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[57]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[56]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[55]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[54]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[53]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[52]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[51]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[50]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[49]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[48]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[47]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[46]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[45]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[44]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[43]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[42]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[41]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[40]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[39]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[38]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[37]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[36]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[35]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[34]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[33]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[32]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rdata[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rresp[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_rresp[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_rlast]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_rvalid]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_awready]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_wready]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_bresp[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_bresp[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_bvalid]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_arready]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rdata[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rresp[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {s_axil_rresp[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports s_axil_rvalid]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awid[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awid[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awid[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awid[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[63]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[62]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[61]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[60]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[59]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[58]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[57]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[56]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[55]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[54]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[53]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[52]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[51]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[50]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[49]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[48]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[47]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[46]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[45]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[44]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[43]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[42]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[41]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[40]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[39]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[38]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[37]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[36]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[35]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[34]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[33]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[32]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awaddr[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awlen[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awsize[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awsize[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awsize[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awburst[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_awburst[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_awvalid]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[127]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[126]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[125]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[124]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[123]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[122]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[121]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[120]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[119]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[118]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[117]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[116]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[115]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[114]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[113]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[112]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[111]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[110]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[109]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[108]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[107]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[106]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[105]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[104]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[103]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[102]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[101]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[100]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[99]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[98]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[97]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[96]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[95]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[94]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[93]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[92]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[91]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[90]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[89]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[88]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[87]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[86]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[85]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[84]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[83]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[82]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[81]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[80]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[79]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[78]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[77]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[76]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[75]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[74]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[73]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[72]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[71]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[70]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[69]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[68]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[67]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[66]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[65]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[64]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[63]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[62]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[61]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[60]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[59]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[58]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[57]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[56]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[55]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[54]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[53]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[52]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[51]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[50]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[49]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[48]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[47]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[46]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[45]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[44]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[43]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[42]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[41]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[40]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[39]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[38]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[37]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[36]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[35]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[34]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[33]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[32]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wdata[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_wstrb[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_wlast]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_wvalid]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_bready]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arid[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arid[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arid[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arid[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[63]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[62]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[61]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[60]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[59]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[58]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[57]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[56]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[55]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[54]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[53]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[52]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[51]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[50]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[49]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[48]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[47]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[46]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[45]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[44]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[43]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[42]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[41]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[40]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[39]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[38]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[37]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[36]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[35]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[34]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[33]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[32]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_araddr[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arlen[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arsize[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arsize[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arsize[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arburst[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {m_axi_arburst[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_arvalid]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports m_axi_rready]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports irq]
set_max_fanout 32.000 [current_design]
set_max_transition 0.5 [current_design]
set_wire_load_mode "top"
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_clock_uncertainty -hold 0.2 [get_clocks clk]
